"""add total_price to bookings

Revision ID: 497bab0a1ef1
Revises: ce96611f041e
Create Date: 2026-08-29 11:16:23.152109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '497bab0a1ef1'
down_revision: Union[str, Sequence[str], None] = 'ce96611f041e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'total_price')
    # ### end Alembic commands ###
